### ISSUE TITLE
Database AutoIncrement problem

### ISSUE THREAD

**Issue by boulec** [rpi-dotcio/phpLicenseWatcher#101]
Hello,

I've noticed the following:
Each time the script "license_util.php" is run through a cron job or (using taskmanager on windows) the "Auto_Increment" for the 'ID' of the license and feature table is incremented. Allthough there are no new rows created in both the tabels.

Depending of the frequency of running the script, this result in the fact at a certain moment that the Auto_increment value gets higher then limit of a small int for the id. As a result in case of a license update and new features are available they are not available through phplicenseWatcher because the ID is to big.

**To Reproduce**
1. Go to 'phpmyadmin and find the current 'auto_increment' for the table features or licenses 
2. Run the 'license_util.php' script
3. See that the value for auto_increment is changed, allthough no rows are added.

**Expected behavior**
Auto_increment should not change.

**Screenshots**
![image](https://user-images.githubusercontent.com/41441292/136217496-3698e327-8f83-4a91-a15c-fd12c6471d73.png)

**Comment by boulec** [comment]
Hello,
I've further studied the problem:
In "license_util.php" - function update_licenses, after the command that post the usage to the db, the number of affected rows is checked. If the number of rows is zero, it assumes that the feature is not available, and it starts commands to insert the feature in the tables. 
This is wrong, the feature can be available but the option 'Is_tracked' set to false. This result also in zero rows affected.  
So this results in trying to insert the feature that has 'is_tracked' set to false each time license_util.php is executed.
The database however has rules set that avoids/blocks the insert of same features. As a result the insert commands are rolled back, but the autoincrement value is incremented.
I've fixed the license_util.php code on my copy. First I check if the feature is available and if the feature is tracked before adding the usage information. 
As I'm not a contributor, I'll attach my license_util.php to this issue.
Regards,
[license_util_php.txt](https://github.com/rpi-dotcio/phpLicenseWatcher/files/7319902/license_util_php.txt)

**Comment by pbailie** [comment]
Thank you for bringing this issue to our attention.  I apologize for not attending to this sooner as another project I am responsible for required very high priority attention.

To be clear about what is happening:  checking the column `is_tracked` is important in that we cannot add usage data for a feature that is not tracked.  Upon zero rows being affected — meaning no usage data was entered — we then attempt to insert the feature and its associated license (comprised of the feature and its managing server).  It is intentional that should the feature/license already exist (e.g. it is in the DB, but not tracked), the insert is ignored.  This is explicit in the SQL queries using `INSERT IGNORE ...`, which is similar to Postgresql's `INSERT ... ON CONFLICT (...) DO NOTHING`.

Logically speaking, this is not wrong.  What went unexpected is that the auto increment would still be incremented on an ignored insert.  Therefore to me, the pertinent question is "Why is the auto increment being incremented when nothing was inserted?"  The answer I found is specific to the InnoDB table engine in MySQL and its algorithms for concurrency and performance.  Those interested can read more about it here:  https://dev.mysql.com/doc/refman/5.7/en/innodb-auto-increment-handling.html

As an aside, I did a test where MySQL was reconfigured with `innodb_autoinc_lock_mode = 0` (default is `1`).  This did prevent auto increment gaps in the `features` table, but not the `licenses` table.

As this issue is based on database level behavior, I prefer a database level solution, which I hope to provide soon.

**Comment by boulec** [comment]
I understand your point of view.
But in my opinion it is better to avoid unnecessary insert-queries than to count on the database settings.
If you can avoid those queries through client-side logic, I think it's better for performance and more robust.
Also, in my case, I'm only interested in a very limited number of licenses out of many. It therefore seems pointless to me to run unnecessary INSERT queries on the database every 15 minutes.
Thanks for your time and work.

**Comment by pbailie** [comment]
I've had conversations with @mcglow2 about this issue.  We're going with a simpler approach to reset the auto increment ID after every transaction.  On the occasion where there are new licenses being added, there could still be gaps in continuity, but those gaps would be small (particularly for those admins who manage only a small set of licenses in total).

However the fix I am currently testing should otherwise keep the auto-increment ID from incrementing.  It ran all last night, and so far so good.
