### ISSUE TITLE
Support for Flexnet Java

### ISSUE THREAD

**Issue by radioactiv** [rpi-dotcio/phpLicenseWatcher#113]
**Is your feature request related to a problem? Please describe.**
ENVI and IDL from Harris Geospatial use the latest flextnet licensing daemon, which is Java based and runs on port 7070.  LMutil can't connect to the service.

**Describe the solution you'd like**
Use the output of their new tool (flexnetlsadmin) to log license usage

**Describe alternatives you've considered**
Writing our own way of tracking license use over time

**Additional context**
The command to get current license usage is `flexnetlsadmin -server http://server-name:7070 - licenses`

The output is:

```
(license_server_url) License Server    : 127.0.0.1:7070

(no_of_features) Number of features    : 68

(no_of_client) Number of clients       : 2
```

**Comment by mcglow2** [comment]
Adding support for this new license tracking software is of interest to us.  We will accept community contributions, or will look into implementing it directly as time allows.  We have yet to see any of the software we track move to this new platform.

Ideally the php code would contact the license server API directly, not using flexnetlsadmin on the command line , since this appears to be a web endpoint.  There does appear to be a json format output option for flexnetlsadmin so at least we dont have to parse text output like from lmutil.

This other software package documents some detailed options that may return more of the data that is needed for tracking.  https://docs.revenera.com/fne/2021_07/adminguide/Content/helplibrary/License_Server_Administrator_Command_line_Tool__Command_Summary.htm#lagquickstart_3380210809_1033271  and https://docs.revenera.com/fne/2021_07/adminguide/Content/helplibrary/View_License_Details.htm#lagcommandlinetool_3088091773_1033761 .

**Comment by radioactiv** [comment]
The vendor that was using this has changed to a different licensing system.

**Comment by radioactiv** [comment]
The vendor that was using this has changed to a different licensing system.
