### ISSUE TITLE
PHP Error: lmgrd is not running: License server machine is down or not responding

### ISSUE THREAD

**Issue by Hephraak** [rpi-dotcio/phpLicenseWatcher#129]
I installed the Licence Watcher on Ubuntu 20.04. and try to receive data from a Windows License-Server with the following command:

```
lmutil lmstat -c 28000@XXX.XXX.XX.XXX -a
```

Then I got this Error:

License server status: 28000@XX-XXXX-XX
    License file(s) on XX-XXXX-XX: 28000@XXX.XXX.XX.XXX:

lmgrd is not running: License server machine is down or not responding. (-96,7:2 "No such file or directory")

The Problem **does not** occur when I use the same command from a Windows-PC.

**Comment by pbailie** [comment]
We at rpi-dotcio are not developers for Flexlm.  This fork of PHP License Watcher is a web interface and data graph for Flexlm's lmutil and Mathematica's monitorlm, but we are not affiliated with Flexlm or Mathematica.  So as much as I'd like to help, I lack the expertise to help with this issue.

I'll leave this issue open for a little while in case someone else has any insight and can assist.

**Comment by turbo2ltr** [comment]
For anyone looking for the answer.... I had this same issue.  On the linux side, `lmstat` is able to get the name of the PC (it's unresolvable from the linux box so I'm using `port@IP`) so it seems to be talking to it.  But get the same error as the OP.  On windows, the command works fine.  I'm using the version distributed with the software (copyright 2024) but also tried a different one I found online (copyright 2021).

Turns out this specific error `(-96,7:2 "No such file or directory")`  occurs when the host name in the license file is not resolvable by the client that is checking, like in my case. Changing the host name to the IP address in the license file allowed it to work.
