### ISSUE TITLE
parselog.php and license_util.php are not working

### ISSUE THREAD

**Issue by ishackigozi** [rpi-dotcio/phpLicenseWatcher#137]
**Describe the bug**

**To Reproduce**
1. Go to '...' the parselog.php and license_util.php are getting error 500 when I use wget. 

[root@sralic02prdal html]# php /var/www/html/license_cache.php >> /var/www/html/logs/license_cache.log
[root@sralic02prdal html]# wget -O - http://105.165.31.175/parselog.php >> /var/www/html/logs/license_parse.log
--2023-06-01 15:15:33--  http://105.165.31.175/parselog.php
Connecting to 105.165.31.175:80... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2023-06-01 15:15:33 ERROR 500: Internal Server Error.

[root@sralic02prdal html]# php parselog.php
PHP Warning:  require_once(DB.php): failed to open stream: No such file or directory in /var/www/html/parselog.php on line 22
PHP Fatal error:  require_once(): Failed opening required 'DB.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/parselog.php on line 22
[root@sralic02prdal html]# which php
/usr/bin/php
[root@sralic02prdal html]# wget -O- http://105.165.31.175/license_util.php >> /var/www/html/logs/license_util.log
--2023-06-01 15:16:32--  http://105.165.31.175/license_util.php
Connecting to 105.165.31.175:80... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2023-06-01 15:16:32 ERROR 500: Internal Server Error.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Redhat 8.7

**Comment by ishackigozi** [comment]
@uChoh5fe I cloned the repository in this url https://github.com/rpi-dotcio/phpLicenseWatcher.git. It does not have that file DB.php. Please advise.

**Comment by ishackigozi** [comment]
![php](https://github.com/rpi-dotcio/phpLicenseWatcher/assets/64915345/1e43cd67-d7cd-43c8-93fa-a88ca70cd017)

**Comment by uChoh5fe** [comment]
Hi, according to the screenshot you use the master branch, but in the master there is no `parselog.php` file anymore. Maybe start from a clean `html` directory and clone again.

**Comment by ishackigozi** [comment]
Okay sounds good. Let me give this a shot.

**Comment by ishackigozi** [comment]
Please find the errors above. Can you advise what maybe wrong?

**Comment by ishackigozi** [comment]
[root@html]# php license_alert.php

PHP Notice:  Undefined variable: expiration_array in /var/www/html/license_alert.php on line 42
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/html/license_alert.php on line 42
[root@ html]# php license_util.php

PHP Notice:  Undefined variable: name in /var/www/html/license_util.php on line 55
PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/license_util.php on line 55
PHP Fatal error:  Uncaught Error: Call to a member function close() on bool in /var/www/html/license_util.php:63
Stack trace:
#0 /var/www/html/license_util.php(8): update_servers()
#1 {main}
  thrown in /var/www/html/license_util.php on line 63

**Comment by ishackigozi** [comment]
@uChoh5fe Everything works as expected apart from. 

[root@sralic02prdal html]# php /var/www/html/license_util.php

PHP Fatal error:  Uncaught Error: Call to a member function bind_param() on bool in /var/www/html/license_util.php:56
Stack trace:
#0 /var/www/html/license_util.php(8): update_servers()
#1 {main}
  thrown in /var/www/html/license_util.php on line 56
![image](https://github.com/rpi-dotcio/phpLicenseWatcher/assets/64915345/ddffaf51-2876-4b53-ba03-0ec22e1f8beb)

**Comment by ishackigozi** [comment]
![image](https://github.com/rpi-dotcio/phpLicenseWatcher/assets/64915345/62d24b9d-30f2-45da-893a-2f62d82a537e)

**Comment by uChoh5fe** [comment]
Hi, I am not an expert on executing `php` directly, so I would try with `wget -O - http://105.165.31.175/license_util.php` from commandline. Can you post this output?

**Comment by ishackigozi** [comment]
Hello,
Below is the output.
[root@sralic02prdal ~]#  wget -O - http://105.165.31.175/license_util.php
--2023-06-07 07:43:20--  http://105.165.31.175/license_util.php
Connecting to 105.165.31.175:80... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2023-06-07 07:43:20 ERROR 500: Internal Server Error.

**Comment by ishackigozi** [comment]
Hello @uChoh5fe, I was able to figure everything out. The issue was with the database permissions. 
I would like to restrict the admininstrator page. Please kindly advise how I can achieve this.

**Comment by uChoh5fe** [comment]
Hi @ishackigozi, I believe this is outside the scope of `phpLicenseWatcher` ;-) But google for `.htaccess`. Untested I found eg:
```
 <FilesMatch "servers_admin.php">
 AuthName "Member Only"
 AuthType Basic
 AuthUserFile /home/username/public_html/.htpasswd
 require valid-user
 </FilesMatch>
```

**Comment by uChoh5fe** [comment]
If you want to install PHPMailer via Composer, you can follow these steps:

1. Open your web browser and go to the following website: [https://letmegooglethat.com/?q=Install+phpmailer+via+composer](https://letmegooglethat.com/?q=Install+phpmailer+via+composer).

2. Once you're on the website, you'll see the search results for "Install phpmailer via composer." Click on any of the search results that provide a tutorial or guide on how to install PHPMailer.

3. The tutorial or guide will explain the installation process step by step. It will likely include instructions on how to set up Composer if you haven't done so already.

4. Follow the instructions carefully, which may involve opening a command line interface (such as Terminal on Mac or Command Prompt on Windows) and running Composer commands.

5. Make sure you have a working internet connection because Composer will download and install the necessary files for PHPMailer.

6. Once the installation is complete, you should be able to use PHPMailer in your PHP projects. The tutorial or guide may also provide examples or code snippets to help you get started.

Remember to always double-check the tutorial or guide you're following to ensure you're installing the correct version of PHPMailer and using the most up-to-date instructions.

I hope this helps! Let me know if you have any more questions.

**Comment by ishackigozi** [comment]
@uChoh5fe thank you so much. I am very grateful for all your assistance.
