### ISSUE TITLE
Usage graphs not showing

### ISSUE THREAD

**Issue by nigelhorne** [rpi-dotcio/phpLicenseWatcher#36]
Apache's logs showed the need to install DB.php, so a bit of research showed this is needed:

`yum install php-pear-DB`

Now I'm seeing this cryptic error "DB Error: extension not found" and this in the error logs:

`[Fri Nov 06 15:54:41.187925 2020] [proxy_fcgi:error] [pid 1889:tid 140485091915520] [client xxx.xxx.xxx.xxx:57054] AH01071: Got error 'PHP message: PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /usr/share/pear/DB.php on line 774', referer: https://xxxx.example.com/index.php
`

**Comment by mcglow2** [comment]
@nigelhorne  I might suggest using the database branch, instead of master, as a source for a new install at this point.  It is a major update that has a far better schema on the db side.

**Comment by nigelhorne** [comment]
That's even worse :-(. I now get this:

`DB Error: extension not found`

and nothing works at all

**Comment by pbailie** [comment]
That means the extension isn't loaded.  In another issue, you mentioned having installed composer.  Composer is then used to load DB (and HTML_Table).  Make sure the composer.json file is copied with the site code.  Then `cd` over to the site code and execute composer.  (do not execute composer as root).
```bash
$ composer install
```

Also, if you just want to test this system -- the vagrant development box will automatically setup composer and other pieces for you.  This is **NOT** suitable for production, however.

I wrote a readme on how to use Vagrant, which can be viewed in the `vagrant_provision` folder.  Please understand that this is in active development and the database branch is no better than a "nightly" release.

@mcglow2 Looks to me we could benefit if I wrote a setup script for production.  The Vagrant provision scripts might be a starting place, but some things would need to be changed for proper usage in production.

**Comment by nigelhorne** [comment]
Thanks, I tried that and I got this message.  The site still doesn't work:

```
$ composer install
Loading composer repositories with package information
Initializing PEAR repository https://pear.php.net
Warning from https://packagist.org: You are using an outdated version of Composer. Composer 2.0 is now available and you should upgrade. See https://getcomposer.org/2
Updating dependencies (including require-dev)


  [ErrorException]
  "continue" targeting switch is equivalent to "break". Did you mean to use "
  continue 2"?


install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

```

**Comment by nigelhorne** [comment]
I should add that this is CentOS7.

**Comment by pbailie** [comment]
The setup instructions hadn't yet been updated to reflect the changes I have been working on.  Sorry about that.  So I did some rudimentary updates to the setup instructions in the 'database' branch's [`readme.md`](https://github.com/rpi-dotcio/phpLicenseWatcher/blob/database/README.md).

We are developing with Ubuntu 20.04, although I don't see a reason why it shouldn't work in CentOS.  Right now the challenge appears to be just getting all the pieces in place.

Composer is a dependency manager for projects written in PHP.  Pear is a repository of PHP code libraries -- of which we use the DB and HTML_Table libraries.  Pear hosts the libraries, and Composer retrieves and installs them for our use.  And while we could rely on `apt`, `yum`, etc. for the Pear libraries, Composer provides greater flexibility should we need to expand the project with another library.

As for the Composer warnings and exceptions...
```
Warning from https://packagist.org: You are using an outdated version of Composer.
Composer 2.0 is now available and you should upgrade. See https://getcomposer.org/2
```
I get the same thing from Composer provided by Canonical (via `apt`).  It has not (yet?) hindered my development work, so I ignore it.  But this can be fixed by installing Composer, manually.

```
[ErrorException]
"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?
```
This is a PHP code exception generated by Composer itself.  The gist is that `continue` is normally used to cancel a loop cycle part-way and start the next cycle, but it doesn't work that way when nested in a `switch/case` block.  In which case `continue 2` becomes necessary.

A quick poke at Google implies that this is a problem with some versions of Composer, which further implies that CentOS is managing a version of Composer with this bug.  🙁  You may need to remove Composer via `yum` and manually install it.  Instructions for a manual install are here:  https://getcomposer.org/download/

**Comment by nigelhorne** [comment]
Thanks, but this is a production machine, and phpLicenseWatcher is the only software that needs composer, so building a version just for this is not something I want to do.  I'll just have to hope that RedHat fixes it.

**Comment by nigelhorne** [comment]
The manual version doesn't work either:

```
$ composer install


  [RuntimeException]
  The PEAR repository has been removed from Composer 2.0
```

**Comment by pbailie** [comment]
Well, we can't have the latest Composer rejecting our dependencies.  Let me investigate this further and see what solution I can find.  I'll try to update within a few business days.

**Comment by pbailie** [comment]
@mcglow2  and I have determined the best course for us would be to re-implement our Pear dependencies, locally.  (This time) it shouldn't be a major engineering task, and staying with Pear seems more trouble than it is worth.

I've opened #38 for this task.

**Comment by pbailie** [comment]
@nigelhorne I have completed removing the pear dependencies (per #38) within the database branch.  You are welcome to try it out and let us know how well it is (or isn't) working.  Composer is no longer used (for now).

**Comment by nigelhorne** [comment]
Actually I couldn't wait for the database branch to be finished, so I've rolled out the master branch with a few changes, such as fixing the path to the config file.  So for the moment we have no more plans to upgrade.  Thanks.
