### ISSUE TITLE
config.php suggestion (minor)

### ISSUE THREAD

**Issue by nigelhorne** [rpi-dotcio/phpLicenseWatcher#39]
I believe this line (this is in the master branch):

`$dsn="pgsql://license:license@localhost/license";`

Should say:

`$dsn="$db_type://$db_username:$db_password@$db_hostname/$db_database";`

Is the format the same for MySQL?  If would help to have an example for that, or have it documented, in the config.php file

**Comment by pbailie** [comment]
`$dsn` is used by pear/DB.  I have already deprecated it (in the database branch) as a config var since it is just a concat'd string of other config vars.  Instead, I had the dsn built when connecting to the DB.  But since pear/DB is being removed -- it won't matter.

(pear/DB is being replaced by PHP's native MySQL API, which I believe also works with MariaDB).

The config file used by Vagrant is cleaner and better commented.  (`vagrant_provision/config/config.php`)  Although the version in the database branch (below) is newer and currently the model I use for testing.

(commented out vars are disabled for testing -- they'll be removed once I am confident their absence doesn't break something)
https://github.com/rpi-dotcio/phpLicenseWatcher/blob/c8efe9d442c10b91fe2b362387e9503138bb8542/vagrant_provision/config/config.php#L1-L29
